In [1]:
import numpy as np,pandas as pd
from sklearn.linear_model import LinearRegression
df=pd.DataFrame({"x":(1,2,3,4,5),"y":(12,34,2,67,98)})
df

x   y
0  1  12
1  2  34
2  3   2
3  4  67
4  5  98

In [2]:
input=df[["x"]]
output=df["y"]
tm=LinearRegression()
tm.fit(input,output)

LinearRegression()

In [3]:
tm.coef_

array([20.5])

In [4]:
tm.intercept_

-18.90000000000002

In [6]:
prd=tm.predict(input)
prd

array([ 1.6, 22.1, 42.6, 63.1, 83.6])

In [8]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(output,prd)
mse

424.14000000000004

In [9]:
Df=pd.DataFrame({"S":(1,2,3,4,5),"z":(6,7,8,9,10)})
inp=Df[["S"]]
otpt=Df["z"]
tm.fit(inp,otpt)

LinearRegression()

In [10]:
tm.coef_

array([1.])

In [11]:
tm.intercept_

4.999999999999999

In [13]:
prd=tm.predict(inp)
prd

array([ 6.,  7.,  8.,  9., 10.])

In [14]:
from sklearn.metrics import mean_squared_error
mean_squared_error(otpt,prd)

1.5777218104420237e-31